import Head from 'next/head';
import styles from '@/styles/Organization.module.css';
import { withPageAuthRequired, getSession } from '@auth0/nextjs-auth0';
import { getSupabase } from '../../utils/supabase';
import Link from 'next/link';
import { Navbar } from '../../components/Navbar';
import { useState } from 'react';
import {
  FormGroup,
  FormControl,
  InputLabel,
  Input,
  TextField,
  Box,
  Button,
} from '@mui/material';

// Post new projects
export default function all({ userProfile }) {
  const [projectForm, setProjectForm] = useState({
    title: '',
    location: '',
    about: '',
  });

  const handleSubmit = (event) => {
    event.preventDefault();
    console.log('projectForm', projectForm);
  };

  const handleChange = (event) => {
    setProjectForm((prevProjectForm) => {
      return {
        ...projectForm,
        [event.target.name]: event.target.value,
      };
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar userProfile={userProfile} />
      <main className={styles.main}>
        <Box className={styles.post_background}>
          <FormGroup className={styles.post_form_style}>
            <FormControl className={styles.post_form_line}>
              <InputLabel>Project Name</InputLabel>
              <Input
                value={projectForm.title}
                name='title'
                onChange={handleChange}
              />
            </FormControl>
            <FormControl className={styles.post_form_line}>
              <InputLabel>Location</InputLabel>
              <Input
                value={projectForm.location}
                name='location'
                onChange={handleChange}
              />
            </FormControl>
            <FormControl className={styles.post_form_textfield}>
              <TextField
                placeholder='About your project'
                value={projectForm.about}
                name='about'
                onChange={handleChange}
              />
            </FormControl>
            <Button type='submit' variant='contained' onClick={handleSubmit}>
              Submit
            </Button>
          </FormGroup>
        </Box>
      </main>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps({ req, res }) {
    const {
      user: { accessToken, sub },
    } = await getSession(req, res);

    const supabase = getSupabase(accessToken);
    let userProfile = null;

    try {
      // if no user has user_id of sub, create new user
      const { data } = await supabase
        .from('user')
        .upsert({ user_id: sub }, { onConflict: 'user_id' })
        .select();

      userProfile = data[0];
    } catch (e) {
      console.error(e.message);
    }

    return {
      props: { userProfile },
    };
  },
});
