import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { withPageAuthRequired, getSession } from "@auth0/nextjs-auth0";
import { getSupabase } from "../utils/supabase";

import { Navbar } from "./components/Navbar";
import { Signup } from "./components/Signup";

export default function Home({ user }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user} />
      <main className={styles.main}>

        {!user.role
          ? <>
            <h1>New account form</h1>
            <Signup user={user} />
          </>
          : <>
            <h1>Volunteer Vision</h1>
            <h1>{user.role}</h1>
            Welcome {user.name}!{' '}
          </>}
      </main>
    </>
  );
}

export const getServerSideProps = withPageAuthRequired({
  async getServerSideProps({ req, res }) {
    const {
      user: { accessToken, sub },
    } = await getSession(req, res)

    const supabase = getSupabase(accessToken)
    let user = null;

    try {
      // if no user has user_id of sub, create new user
      const { data } = await supabase.from('user').upsert({ user_id: sub }, { onConflict: 'user_id' }).select()
      user = data[0];
    }
    catch (e) {
      console.error(e.message)
    }

    return {
      props: { user },
    }
  },
});